### ISSUE TITLE
Please Tidy This Repo: Coordinate development across openscad vscode LSP plugins or sunset/deprecate

### ISSUE THREAD

**Issue by elasticdotventures** [JulianGmp/vscode-openscad-formatter#2]
Hi @JulianGmp 

I'm requesting you tidy the README of this repo to explain the current project status.

it looks like this project hasn't been updated in the last 6 months, there is a small but growing community of OpenSCAD LSP users both in potentially outside vs-code who want to develop the LSP. 

Would you consider removing this repo from the VS Code marketplace / or at least updating your README to indicate the status so there's reduced confusion.

(trying to keep the OpenSCAD plugins in VS code marketplace tidy)

**Comment by JulianGmp** [comment]
Hi,

right now the big issue is that includes will mess up the formatting (#1).
I have a duct-tape like "solution" to that sketched up but not implemented and I haven't worked on it because I frankly haven't been using openscad myself.

When it comes to the LSP, this extension doesn't mess with it at all, it simply calls an external tool.
The only extension I'm aware of is [Antyos.openscad](https://marketplace.visualstudio.com/items?itemName=Antyos.openscad), but that one doesn't include formatting from what I've read.

**Comment by JulianGmp** [comment]
I also just closed that one issue, this extension should be more broadly applicable now.

As I said this extension has nothing to do with the LSP, so I don't really understand your request to remove this extension entirely?

I added a note referring to Antyos' extension for syntax and other language features in the readme.
